### ISSUE TITLE
try ... catch -> throw pattern

### ISSUE THREAD

**Issue by jcuenod** [just1689/postgrest-java-client#1]
In `src/main/java/za/co/captain/generic/GenericRepository.java` you seem to be following a pattern of

```
public void [methodName]() throws CaptainException {
  try { 
    //bunch of code
  } catch (Exception e) {
    throw new CaptainException(e, "[methodName]");
  }
}
```

Is this a useful pattern? Seems pointless since `methodName` would be in the stacktrace anyway. I guess the only thing that this might be useful for that I'm not accounting for is that `CaptainException`s could add more debugging data to the stacktrace but I'm not sure what your decorators are doing.

**Comment by just1689** [comment]
Well this is embarrassing. I wasn't really dealing with anything yet there. I added the CaptainException hoping that some clear boundaries would emerge and allow a clear definition for responsibilities and the type of feedback that would be helpful a layer above when something goes wrong. Haven't hit that point yet, so the heresy remains.

**Comment by jcuenod** [comment]
fair enough...
